{{- if .Values.grafana.ext.datasources.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    grafana_datasource: 'true' # default value for: sidecar.datasources.label
stringData:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
{{- if .Values.grafana.ext.datasources.prometheus.enabled }}
      - name: Prometheus
        type: prometheus
        url: {{ include "grafana.ext.prometheus.server.fullname" . }}
        isDefault: true
        access: proxy
        editable: true
{{- end }}
{{- end }}