{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.keycloak.name }}-secret
type: Opaque
stringData:
  usernameSecret: {{ .Values.keycloak.db.user }}
  passwordSecret: {{ .Values.keycloak.db.password }}
{{- end }}