{{- if .Values.traefik.middleware.auth.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "app.fullname" . }}-auth
  labels:
{{ include "app.labels.common" $ | indent 4 }}  
type: Opaque  
data: 
  users: {{ .Values.traefik.middleware.auth.users }}
{{- end }}