name: Update helm chart dependencies

on:
  workflow_dispatch:
  repository_dispatch:
    types: [helm-update-deps]
  schedule:
    - cron: "0 1 * * 2"
jobs:
  update:
    uses: onecx/ci-product/.github/workflows/helm-update-deps.yml@v1
    secrets: inherit
